---
k3s_version: v1.31.2+k3s1
k3s_server_args: "--tls-san {{ hostvars[groups['k3s_cluster'][0]]['ansible_host'] }}"

# Apps versions
argocd_version: 7.7.8
longhorn_version: 1.7.2
prometheus_stack_version: 66.3.1
traefik_version: 3.1.5
authentik_version: 2024.6.1
rancher_version: 2.9.4

# Apps config
grafana_oauth_client_id: "your_client_id_here"
grafana_oauth_client_secret: "your_client_secret_here"
argocd_admin_password: "{{ vault_argocd_admin_password }}"

# Set to false if you don't want to deploy Rancher
deploy_rancher: true  

# Domain configuration
domain: your-domain.com
email: your-email@example.com

# Authentik configuration
authentik_secret_key: "{{ vault_authentik_secret_key }}"
authentik_postgresql_password: "{{ vault_authentik_postgresql_password }}"

# Server configuration
perform_full_upgrade: false
disable_ipv6: false

# Time zone configuration
timezone: "UTC"  # Change this to your desired time zone, e.g., "America/New_York"

