- name: Create a user {{ user }}
  user:
    name: "{{ user }}"
    create_home: yes
    shell: /bin/bash
    state: present
    groups: sudo
    generate_ssh_key: yes
    ssh_key_type: rsa

- name: Ensure correct ownership for ansible home directory
  ansible.builtin.file:
    path: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
    recurse: true
    
- name: Allow passwordless sudo for {{ user }} 
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Set authorized key for user {{ user }} copying it from current user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

