---
- name: Check if Homepage is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: homepage
    namespace: homepage
  register: Homepage_check
  ignore_errors: true
  when: deploy_homepage | bool

- name: Fetch Homepage Helm chart information
  kubernetes.core.helm_info:
    name: homepage
    release_namespace: homepage
  register: Homepage_helm_info
  ignore_errors: true
  when: deploy_homepage | bool

- name: Deploy or upgrade Homepage
  kubernetes.core.helm:
    name: homepage
    chart_ref: jameswynn/homepage
    chart_version: "{{ homepage_version }}"
    release_namespace: homepage
    create_namespace: true
    values: "{{ lookup('template', 'values-homepage.yml.j2') | from_yaml }}"
  when: deploy_homepage | bool

- name: Wait for Homepage pod to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: homepage
    label_selectors:
      - app.kubernetes.io/name=homepage
  register: homepage_pod
  until:
    - homepage_pod.resources is defined
    - homepage_pod.resources | length > 0
    - homepage_pod.resources[0].status.phase == "Running"
  retries: 30
  delay: 10
  when: deploy_homepage | bool

- name: Install python3 kubernetes on localhost
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
  delegate_to: localhost
  when: deploy_homepage | bool

- name: Copy icons to pod
  kubernetes.core.k8s_cp:
    namespace: homepage
    pod: "{{ homepage_pod.resources[0].metadata.name }}"
    local_path: "{{ role_path }}/homepage/icons"
    remote_path: "/app/public/"
    state: to_pod
  delegate_to: localhost
  when:
    - deploy_homepage | bool
    - homepage_pod.resources is defined
    - homepage_pod.resources | length > 0
