---
- name: Check if Home Assistant is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: home-assistant
    namespace: home-assistant
  register: homeassistant_check
  ignore_errors: true
  when: deploy_homeassistant | bool

- name: Fetch Home Assistant Helm chart information
  kubernetes.core.helm_info:
    name: home-assistant
    release_namespace: homeassistant
  register: homeassistant_helm_info
  ignore_errors: true
  when: deploy_homeassistant | bool

- name: Deploy or upgrade multus-cni
  kubernetes.core.helm:
    name: multus-cni
    chart_ref: bitnami/multus-cni
    release_namespace: home-assistant
    create_namespace: true
    chart_version: 2.2.7
    wait: true
    wait_timeout: 5m
  register: homeassistant_deploy
  when: deploy_homeassistant | bool

- name: Create NetworkAttachmentDefinition
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: "k8s.cni.cncf.io/v1"
      kind: NetworkAttachmentDefinition
      metadata:
        name: iot-network
        namespace: home-assistant
      spec:
        config: '{
                    "cniVersion": "0.3.1",
                    "type": "macvlan",
                    "master": "<network_interface>",
                    "mode": "bridge",
                    "ipam": {
                      "type": "dhcp"
                    }
                  }'
  when: deploy_homeassistant | bool

- name: Deploy or upgrade Home Assistant
  kubernetes.core.helm:
    name: home-assistant
    chart_ref: pajikos/home-assistant
    release_namespace: home-assistant
    create_namespace: true
    values: "{{ lookup('template', 'values-homeassistant.yml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 5m
  register: homeassistant_deploy
  when: deploy_homeassistant | bool

