---

- name: Add Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: jellyfin, url: "https://jellyfin.github.io/jellyfin-helm" }
  tags:
    - apps
    - apps:repos


- import_tasks: jellyfin.yml
  tags:
    - apps
    - apps:jellyfin




