---

- name: Add Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: jellyfin, url: "https://jellyfin.github.io/jellyfin-helm" }
    - { name: jameswynn, url: "https://jameswynn.github.io/helm-charts" }
    - { name: audiobookshelf, url: "https://gitlab.com/api/v4/projects/57546317/packages/helm/release" }
    - { name: pajikos, url: "http://pajikos.github.io/home-assistant-helm-chart/" }
    - { name: bitnami, url: "https://charts.bitnami.com/bitnami" }
    - { name: multus, url: "https://rke2-charts.rancher.io" }
    - { name: gabe565, url: "https://charts.gabe565.com" }
  tags:
    - apps
    - apps:repos
    - apps:jellyfin
    - apps:homepage
    - apps:audiobookshelf
    - apps:homeassistant

# - import_tasks: jellyfin.yml
#   tags:
#     - apps
#     - apps:jellyfin

- import_tasks: homepage.yml
  tags:
    - apps
    - apps:homepage

- import_tasks: audiobookshelf.yml
  tags:
    - apps
    - apps:audiobookshelf

- import_tasks: homeassistant.yml
  tags:
    - apps
    - apps:homeassistant
    - apps:smarthome

- import_tasks: tandoor.yml
  tags:
    - apps
    - apps:tandoor
