---
- name: Deploy Tandoor Recipe Manager
  block:
    - name: Generate secure passwords
      ansible.builtin.set_fact:
        tandoor_db_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
        tandoor_postgres_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
        tandoor_secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters,digits') }}"
      no_log: true

    - name: Create Tandoor namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: tandoor
        state: present

    - name: Create Tandoor secrets
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: recipes
            namespace: tandoor
          type: Opaque
          stringData:
            postgresql-password: "{{ tandoor_db_password }}"
            postgresql-postgres-password: " {{ tandoor_postgres_password }}"
            secret-key: "{{ tandoor_secret_key }}"
