---

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    port: '22'

- name: Allow NTP through UFW
  community.general.ufw:
    rule: allow
    port: '123'
    proto: udp

- name: Allow HTTP through UFW
  community.general.ufw:
    rule: allow
    port: '80'

- name: Allow HTTPS through UFW
  community.general.ufw:
    rule: allow
    port: '443'

- name: Open required ports for k3s
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '6443'  # Kubernetes API
    - '2379'  # etcd client port
    - '2380'  # etcd peer port
    - '9345'  # k3s internal

- name: Allow Kubelet through UFW
  community.general.ufw:
    rule: allow
    port: '10250'

