---
- name: Import configuration tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - config

- name: Import firewall tasks
  ansible.builtin.import_tasks: firewall.yml
  tags:
    - config
    - config:firewall

- name: Import tailscale tasks
  ansible.builtin.import_tasks: tailscale.yml
  tags:
    - config
    - config:tailscale
