---
- import_tasks: config.yml
  tags:
    - config

- import_tasks: firewall.yml
  tags:
    - config
    - config:firewall

- import_tasks: tailscale.yml
  tags:
    - config
    - config:tailscale