- name: Set up Tailscale repository
  block:
    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Start Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true

- name: Connect to Tailscale network
  ansible.builtin.command: >
    tailscale up
    --authkey={{ tailscale_key }}
    --hostname={{ inventory_hostname }}
    --accept-dns=false
    --accept-routes
  register: tailscale_result
  changed_when: "'Success.' in tailscale_result.stdout"
  failed_when:
    - tailscale_result.rc != 0
    - "'already authenticated' not in tailscale_result.stderr"
