---
- name: Check if Traefik is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: traefik
    namespace: traefik
  register: traefik_check
  ignore_errors: true

- name: Fetch Traefik Helm chart information
  kubernetes.core.helm_info:
    name: traefik
    release_namespace: traefik
  register: traefik_helm_info
  ignore_errors: true

- name: Deploy or upgrade Traefik
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_version }}"
    release_namespace: traefik
    create_namespace: yes
    values:
      additionalArguments:
        - "--certificatesresolvers.le.acme.email={{ email }}"
        - "--certificatesresolvers.le.acme.storage=/data/acme.json"
        - "--certificatesresolvers.le.acme.tlschallenge=true"
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 128Mi
      ports:
        web:
          redirectTo: websecure
      service:
        type: LoadBalancer
    wait: yes
    wait_timeout: 300
  when: >
    traefik_check.resources | length == 0 or
    traefik_helm_info.status is defined and
    traefik_helm_info.status.chart_version is version(traefik_version, '<')
  register: traefik_deploy
  until: traefik_deploy is succeeded
  retries: 3
  delay: 10

- name: Wait for Traefik to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: traefik
    label_selectors:
      - app.kubernetes.io/name=traefik
  register: traefik_pods
  until: >
    traefik_pods.resources | length > 0 and
    (traefik_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 20
  delay: 15
  when: traefik_deploy is changed

- name: Get Traefik LoadBalancer IP
  kubernetes.core.k8s_info:
    kind: Service
    name: traefik
    namespace: traefik
  register: traefik_service
  until: >
    traefik_service.resources | length > 0 and
    traefik_service.resources[0].status is defined and
    traefik_service.resources[0].status.loadBalancer is defined and
    traefik_service.resources[0].status.loadBalancer.ingress is defined and
    traefik_service.resources[0].status.loadBalancer.ingress | length > 0
  retries: 30
  delay: 10
  when: traefik_deploy is changed

- name: Display Traefik LoadBalancer IP
  debug:
    msg: "Traefik LoadBalancer IP: {{ traefik_service.resources[0].status.loadBalancer.ingress[0].ip }}"
  when: traefik_deploy is changed and traefik_service.resources | length > 0