---
- name: Check if Authentik is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: authentik-server
    namespace: authentik
  register: authentik_check
  ignore_errors: true

- name: Fetch Authentik Helm chart information
  kubernetes.core.helm_info:
    name: authentik
    release_namespace: authentik
  register: authentik_helm_info
  ignore_errors: true

- name: Deploy or upgrade Authentik
  kubernetes.core.helm:
    name: authentik
    chart_ref: authentik/authentik
    chart_version: "{{ authentik_version }}"
    release_namespace: authentik
    create_namespace: yes
    values: "{{ lookup('template', 'values-authentik.yml.j2') | from_yaml }}"
    wait: yes
    wait_timeout: 1m 
  when: >
    authentik_check.resources | length == 0 or
    (authentik_helm_info.status is defined and
     authentik_helm_info.status.chart_version is defined and
     authentik_helm_info.status.chart_version is version(authentik_version, '<'))
  register: authentik_deploy
  until: authentik_deploy is succeeded
  retries: 3
  delay: 10

- name: Wait for Authentik to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: authentik
    label_selectors:
      - app.kubernetes.io/name=authentik
  register: authentik_pods
  until: >
    authentik_pods.resources | length > 0 and
    (authentik_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 20
  delay: 30
  when: authentik_deploy is changed