---
- name: Check if GitLab is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: gitlab-webservice-default
    namespace: gitlab
  register: gitlab_check
  ignore_errors: true
  when: deploy_gitlab | bool

- name: Fetch GitLab Helm chart information
  kubernetes.core.helm_info:
    name: gitlab
    release_namespace: gitlab
  register: gitlab_helm_info
  ignore_errors: true
  when: deploy_gitlab | bool

- name: Deploy or upgrade GitLab
  kubernetes.core.helm:
    name: gitlab
    chart_ref: gitlab/gitlab
    chart_version: "{{ gitlab_version }}"
    release_namespace: gitlab
    create_namespace: true
    values: "{{ lookup('template', 'values-gitlab.yml.j2') | from_yaml }}"
  when: deploy_gitlab | bool
  register: gitlab_deploy

- name: Wait for GitLab to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: gitlab
    label_selectors:
      - app=webservice
  register: gitlab_pods
  until: >
    gitlab_pods.resources | length > 0 and
    (gitlab_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 30
  delay: 30
  when: deploy_gitlab | bool and gitlab_deploy is changed
