---
- name: Check if Loki is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: loki
    namespace: monitoring
  register: loki_check
  ignore_errors: true
  when: deploy_loki | bool

- name: Fetch Loki Helm chart information
  kubernetes.core.helm_info:
    name: grafana/loki
    release_namespace: monitoring
  register: loki_helm_info
  ignore_errors: true
  when: deploy_loki | bool

- name: Deploy or upgrade Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    chart_version: "{{ loki_version }}"
    release_namespace: monitoring
    create_namespace: yes
    values: "{{ lookup('template', 'values-loki.yml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 10m
  register: loki_deploy
  when: deploy_loki | bool
  until: loki_deploy is succeeded
  retries: 3
  delay: 10

- name: Deploy or upgrade Promtail
  kubernetes.core.helm:
    name: promtail
    chart_ref: grafana/promtail
    chart_version: "{{ promtail_version }}"
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('template', 'values-promtail.yml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 10m
  register: promtail_deploy
  when: deploy_loki | bool