---
- name: Check if Longhorn is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: longhorn-driver-deployer
    namespace: longhorn-system
  register: longhorn_check
  ignore_errors: true

- name: Fetch Longhorn Helm chart information
  kubernetes.core.helm_info:
    name: longhorn
    release_namespace: longhorn-system
  register: longhorn_helm_info
  ignore_errors: true

- name: Deploy or upgrade Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_version }}"
    release_namespace: longhorn-system
    create_namespace: true
    wait: true
    wait_timeout: 10m
    values: "{{ lookup('template', 'values-longhorn.yml.j2') | from_yaml }}"
  register: longhorn_deploy
  until: longhorn_deploy is succeeded
  retries: 3
  delay: 30

- name: Wait for Longhorn to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: longhorn-system
    label_selectors:
      - app=longhorn-manager
  register: longhorn_pods
  until: >
    longhorn_pods.resources | length > 0 and
    (longhorn_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 20
  delay: 30
  when: longhorn_deploy is changed

- name: Ensure Longhorn is the default StorageClass
  kubernetes.core.k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io

- name: Create ingress for longhorn
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: longhorn
        namespace: longhorn-system
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: default-default-headers@kubernetescrd
      spec:
        ingressClassName: traefik
        tls:
          - hosts:
              - longhorn.{{ domain }}
        rules:
          - host: longhorn.{{ domain }}
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: longhorn-frontend
                      port:
                        number: 80

- name: Create servicemonitor for longhorn
  kubernetes.core.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: longhorn-prometheus-servicemonitor
        namespace: longhorn-system
        labels:
          name: longhorn-prometheus-servicemonitor
          release: prometheus
      spec:
        selector:
          matchLabels:
            app: longhorn-manager
        namespaceSelector:
          matchNames:
            - longhorn-system
        endpoints:
          - port: manager

- name: Create alertrules for longhorn
  kubernetes.core.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        labels:
          prometheus: longhorn
          role: alert-rules
        name: prometheus-longhorn-rules
        namespace: monitoring
      spec:
        groups:
        - name: longhorn.rules
          rules:
          - alert: LonghornVolumeActualSpaceUsedWarning
            annotations:
              description: "The actual space used by Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} is at {% raw %}{{$value}}{% endraw %}% capacity for more than 5 minutes."
              summary: "The actual used space of Longhorn volume is over 90% of the capacity."
            expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
            for: 5m
            labels:
              issue: "The actual used space of Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} is high."
              severity: warning
          - alert: LonghornVolumeStatusCritical
            annotations:
              description: "Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} is Fault for more than 2 minutes."
              summary: "Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} is Fault"
            expr: longhorn_volume_robustness == 3
            for: 5m
            labels:
              issue: "Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} is Fault."
              severity: critical
          - alert: LonghornVolumeStatusWarning
            annotations:
              description: "Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} is Degraded for more than 5 minutes."
              summary: "Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} is Degraded"
            expr: longhorn_volume_robustness == 2
            for: 5m
            labels:
              issue: "Longhorn volume {% raw %}{{$labels.volume}}{% endraw %} is Degraded."
              severity: warning
          - alert: LonghornNodeStorageWarning
            annotations:
              description: "The used storage of node {% raw %}{{$labels.node}}{% endraw %} is at {% raw %}{{$value}}{% endraw %}% capacity for more than 5 minutes."
              summary: "The used storage of node is over 70% of the capacity."
            expr: (longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 > 70
            for: 5m
            labels:
              issue: "The used storage of node {% raw %}{{$labels.node}}{% endraw %} is high."
              severity: warning
          - alert: LonghornDiskStorageWarning
            annotations:
              description: "The used storage of disk {% raw %}{{$labels.disk}}{% endraw %} on node {% raw %}{{$labels.node}}{% endraw %} is at {% raw %}{{$value}}{% endraw %}% capacity for more than 5 minutes."
              summary: "The used storage of disk is over 70% of the capacity."
            expr: (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > 70
            for: 5m
            labels:
              issue: "The used storage of disk {% raw %}{{$labels.disk}}{% endraw %} on node {% raw %}{{$labels.node}}{% endraw %} is high."
              severity: warning
          - alert: LonghornNodeDown
            annotations:
              description: "There are {% raw %}{{$value}}{% endraw %} Longhorn nodes which have been offline for more than 5 minutes."
              summary: "Longhorn nodes is offline"
            expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0
            for: 5m
            labels:
              issue: "There are {% raw %}{{$value}}{% endraw %} Longhorn nodes are offline"
              severity: critical
          - alert: LonghornInstanceManagerCPUUsageWarning
            annotations:
              description: "Longhorn instance manager {% raw %}{{$labels.instance_manager}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} has CPU Usage / CPU request is {% raw %}{{$value}}{% endraw %}% for more than 5 minutes."
              summary: "Longhorn instance manager {% raw %}{{$labels.instance_manager}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} has CPU Usage / CPU request is over 300%."
            expr: (longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu) * 100 > 300
            for: 5m
            labels:
              issue: "Longhorn instance manager {% raw %}{{$labels.instance_manager}}{% endraw %} on {% raw %}{{$labels.node}}{% endraw %} consumes 3 times the CPU request."
              severity: warning
          - alert: LonghornNodeCPUUsageWarning
            annotations:
              description: "Longhorn node {% raw %}{{$labels.node}}{% endraw %} has CPU Usage / CPU capacity is {% raw %}{{$value}}{% endraw %}% for more than 5 minutes."
              summary: "Longhorn node {% raw %}{{$labels.node}}{% endraw %} experiences high CPU pressure for more than 5m."
            expr: (longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100 > 90
            for: 5m
            labels:
              issue: "Longhorn node {% raw %}{{$labels.node}}{% endraw %} experiences high CPU pressure."
              severity: warning
