- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  tags:
    - infra
    - infra:helm


- name: Add Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: traefik, url: "https://helm.traefik.io/traefik" }
    - { name: authentik, url: "https://charts.goauthentik.io" }
    - { name: argo, url: "https://argoproj.github.io/argo-helm" }
    - { name: longhorn, url: "https://charts.longhorn.io" }
    - { name: prometheus-community, url: "https://prometheus-community.github.io/helm-charts" }
    - { name: rancher-stable, url: "https://releases.rancher.com/server-charts/stable" }
    - { name: jetstack, url: "https://charts.jetstack.io" }
    - { name: metallb, url: "https://metallb.github.io/metallb" } 
    - { name: gitlab, url: "https://charts.gitlab.io/" } 
    - { name: grafana, url: "https://grafana.github.io/helm-charts"}
    - { name: emberstack , url: "https://emberstack.github.io/helm-charts"}
  tags:
    - infra
    - infra:repos
    - infra:monitoring
    - infra:longhorn

- name: Update Helm repositories
  ansible.builtin.shell: helm repo update
  changed_when: false
  tags:
    - infra
    - infra:repos
    - infra:longhorn

- import_tasks: metallb.yml
  tags:
    - infra
    - infra:metallb

- import_tasks: traefik.yml
  tags:
    - infra
    - infra:traefik

- import_tasks: certs.yml
  tags:
    - infra
    - infra:certs

- import_tasks: prometheus.yml
  tags:
    - infra
    - infra:monitoring
    - infra:prometheus

- import_tasks: longhorn.yml
  tags:
    - infra
    - infra:longhorn

- import_tasks: rancher.yml
  tags:
    - infra
    - infra:rancher

- import_tasks: authentik.yml
  tags:
    - infra
    - infra:authentik

- import_tasks: argocd.yml
  tags:
    - infra
    - infra:argocd

- import_tasks: grafana.yml
  tags:
    - infra
    - infra:monitoring
    - infra:grafana

- import_tasks: gitlab.yml
  tags:
    - infra
    - infra:gitlab

- import_tasks: loki.yml
  tags:
    - infra
    - infra:monitoring
    - infra:loki
    - infra:promtail

