---
- name: Check if MetalLB is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: metallb-controller
    namespace: metallb-system
  register: metallb_check
  ignore_errors: true

- name: Deploy MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "{{ metallb_version }}"
    release_namespace: metallb-system
    create_namespace: true
  when: metallb_check.resources | length == 0

- name: Wait for MetalLB to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: metallb-system
    label_selectors:
      - app.kubernetes.io/name=metallb
  register: metallb_pods
  until: metallb_pods.resources | length > 0 and (metallb_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 10
  delay: 30
  when: metallb_check.resources | length == 0

- name: Create MetalLB IPAddressPool
  kubernetes.core.k8s:
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
          - "{{ tailscale_ip_range }}"

- name: Create MetalLB L2Advertisement
  kubernetes.core.k8s:
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: example
        namespace: metallb-system
      spec:
        ipAddressPools:
          - first-pool
