---
- name: Check if Prometheus Stack is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: prometheus-kube-prometheus-operator
    namespace: monitoring
  register: prometheus_check
  ignore_errors: true

- name: Fetch Prometheus Stack Helm chart information
  kubernetes.core.helm_info:
    name: prometheus
    release_namespace: monitoring
  register: prometheus_helm_info
  ignore_errors: true

- name: Deploy or upgrade Prometheus Stack
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus_stack_version }}"
    release_namespace: monitoring
    create_namespace: yes
    values:
      prometheus:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.tls.certresolver: le
          hosts:
            - prometheus.{{ domain }}
          tls:
            - secretName: prometheus-tls
              hosts:
                - prometheus.{{ domain }}
    wait: yes
    wait_timeout: 1m
  when: >
    prometheus_check.resources | length == 0 or
    (prometheus_helm_info.status is defined and
     prometheus_helm_info.status.chart_version is defined and
     prometheus_helm_info.status.chart_version is version(prometheus_stack_version, '<'))
  register: prometheus_deploy

- name: Wait for Prometheus to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=prometheus
  register: prometheus_pods
  until: >
    prometheus_pods.resources | length > 0 and
    (prometheus_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 30
  delay: 10
  when: prometheus_deploy is changed
