---
- name: Check if Prometheus Stack is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: prometheus-kube-prometheus-operator
    namespace: monitoring
  register: prometheus_check
  ignore_errors: true

- name: Fetch Prometheus Stack Helm chart information
  kubernetes.core.helm_info:
    name: prometheus
    release_namespace: monitoring
  register: prometheus_helm_info
  ignore_errors: true

- name: Deploy or upgrade Prometheus Stack
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus_stack_version }}"
    release_namespace: monitoring
    create_namespace: yes
    values: "{{ lookup('template', 'values-prometheus.yml.j2') | from_yaml }}"
    wait: yes
    wait_timeout: 5m
  register: prometheus_deploy

- name: Create prometheus ingress
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: prometheus
        namespace: monitoring
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: default-default-headers@kubernetescrd
      spec:
        ingressClassName: traefik
        tls:
          - hosts:
              - prometheus.{{ domain }}
        rules:
          - host: prometheus.{{ domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: prometheus-kube-prometheus-prometheus
                      port:
                        number: 9090



- name: Wait for Prometheus to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: monitoring
    label_selectors:
      - app=kube-prometheus-stack-operator
  register: prometheus_pods
  until: >
    prometheus_pods.resources | length > 0 and
    (prometheus_pods.resources | map(attribute='status.phase') | list | unique == ['Running'])
  retries: 30
  delay: 10
  when: prometheus_deploy is changed
