---
- name: Check if traefik is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: traefik-server
    namespace: traefik
  register: traefik_check
  ignore_errors: true

- name: Fetch traefik Helm chart information
  kubernetes.core.helm_info:
    name: traefik
    release_namespace: traefik
  register: traefik_helm_info
  ignore_errors: true

- name: Deploy or upgrade traefik
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_version }}"
    release_namespace: traefik
    create_namespace: true
    values: "{{ lookup('template', 'values-traefik.yml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 5m
  register: traefik_deploy

- name: Configure traefik Middleware
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: default-headers
        namespace: default
      spec:
        headers:
          browserXssFilter: true
          contentTypeNosniff: true
          forceSTSHeader: true
          stsIncludeSubdomains: true
          stsPreload: true
          stsSeconds: 15552000
          referrerPolicy: no-referrer
          contentSecurityPolicy: >-
            default-src 'self';
            script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:;
            style-src 'self' 'unsafe-inline';
            img-src 'self' data: blob:;
            font-src 'self' data:;
            connect-src 'self' ws: wss:;
            worker-src 'self' blob:;
            frame-src 'self';
            media-src 'self';
            object-src 'none';
            frame-ancestors 'self';
            base-uri 'self';
            form-action 'self' https://jellyfin.{{ domain }} https://authentik.{{ domain }} https://argocd.{{ domain }} https://paperless.{{ domain }}
          customFrameOptionsValue: SAMEORIGIN
          customRequestHeaders:
            X-Forwarded-Proto: https


- name: Configure traefik recipya Middleware
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: recipya-headers
        namespace: default
      spec:
        headers:
          browserXssFilter: true
          contentTypeNosniff: true
          customFrameOptionsValue: SAMEORIGIN
          contentSecurityPolicy: >-
            default-src 'self';
            script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://unpkg.com;
            style-src 'self' 'unsafe-inline';
            img-src 'self' data: blob:;
            font-src 'self' data:;
            connect-src 'self' ws: wss: *;
            worker-src 'self' blob:;
            frame-src 'self';
            media-src 'self' blob:;
            object-src 'none';
            form-action 'self';
          customRequestHeaders:
            X-Forwarded-Proto: "https"
            X-Forwarded-Host: "recipya.{{ domain }}"
            X-Forwarded-For: "true"
