---
# Packages 

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: yes
  when: perform_full_upgrade | default(false)

- name: Install required packages
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - fail2ban
      - ufw
      - python3-kubernetes
      - python3-yaml
      - python3-venv
    state: present

# Time

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: '0644'
  notify: Restart chrony

- name: Enable and start chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Allow NTP through UFW
  ufw:
    rule: allow
    port: '123'
    proto: udp

- name: Ensure system clock is synchronized
  command: chronyc makestep
  changed_when: false

# SSH

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart ssh

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart ssh

- name: Set SSH idle timeout
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ClientAliveInterval'
    line: 'ClientAliveInterval 300'
  notify: Restart ssh

- name: Set SSH client alive count max
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ClientAliveCountMax'
    line: 'ClientAliveCountMax 3'
  notify: Restart ssh