- name: Set up Tailscale repository
  block:
    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
  become: true

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
  become: true

- name: Start Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: yes
  become: true

- name: Connect to Tailscale network
  ansible.builtin.command: tailscale up --authkey={{ vault_tailscale_key }}
  args:
    creates: /var/lib/tailscale/tailscaled.state
  when: vault_tailscale_key is defined
  become: true