---
- name: 01 Create vault and install collections
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: 01_local
      tags:
        - local

- name: 02 Check if ansible user exists and create if necessary
  hosts: all
  gather_facts: false
  vars:
    ansible_user: "{{ ansible_initial_user }}"
  tasks:
    - name: Try to connect as ansible user
      wait_for_connection:
        timeout: 5
      ignore_errors: true
      vars:
        ansible_user: "{{ user }}"
      register: connection_test
      tags: config

    - name: Set fact for initial setup
      set_fact:
        initial_setup: "{{ connection_test is failed }}"
      tags: config

    - name: Create ansible user
      include_role:
        name: 02_create_user
      when: initial_setup | default(false)
      tags: config

- name: 03 Prepare and harden servers
  hosts: all
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 03_base_config
      tags:
        - config

- name: 04 Deploy k3s cluster
  hosts: k3s_cluster
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 04_k3s
      tags:
        - k3s

- name: 05 Deploy infrastructure applications
  hosts: k3s_cluster[0]
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 05_infra
      tags:
        - infra

- name: 06 Deploy applications
  hosts: k3s_cluster[0]
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 06_apps
      tags:
        - apps
