---
- name: Check if ansible user exists and create if necessary
  hosts: all
  gather_facts: false
  vars:
    ansible_user: "{{ ansible_initial_user }}"
  tasks:
    - name: Try to connect as ansible user
      wait_for_connection:
        timeout: 5
      ignore_errors: yes
      vars:
        ansible_user: "{{ user }}"
      register: connection_test

    - name: Set fact for initial setup
      set_fact:
        initial_setup: "{{ connection_test is failed }}"

    - name: Create ansible user
      include_role:
        name: 02_create_user
      when: initial_setup | default(false)

- name: Create vault
  hosts: localhost
  become: true
  roles:
    - role: 01_local
      tags:
        - local
        - vault

- name: Prepare and harden servers
  hosts: all
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 03_base_config
      tags:
        - config
        - config:firewall
        - config:tailscale

- name: Deploy k3s cluster
  hosts: k3s_cluster
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 04_k3s
      tags:
        - k3s

- name: Deploy infrastructure applications
  hosts: k3s_cluster[0]
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 05_infra
      tags:
        - infra

- name: Deploy applications
  hosts: k3s_cluster[0]
  become: true
  vars:
    ansible_user: "{{ user }}"
  roles:
    - role: 06_apps
      tags:
        - apps
        - apps:helm
        - apps:repos
        - apps:traefik
        - apps:authentik
        - apps:argocd
        - apps:longhorn
        - apps:monitoring
        - apps:rancher