---
- name: Prepare and harden servers
  hosts: all
  roles:
    - { role: 01_base_config, tags: ['config', 'prep'] }

- name: Deploy k3s cluster
  hosts: all
  roles:
    - { role: 02_k3s, tags: ['k3s'] }

- name: Deploy applications
  hosts: k3s_cluster[0]
  roles:
    - role: 03_apps
      tags:
        - apps
        - apps:helm
        - apps:repos
        - apps:traefik
        - apps:authentik
        - apps:argocd
        - apps:longhorn
        - apps:monitoring
        - apps:rancher