---
- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  tags:
    - apps
    - apps:helm

- name: Add Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: traefik, url: "https://helm.traefik.io/traefik" }
    - { name: authentik, url: "https://charts.goauthentik.io" }
    - { name: argo, url: "https://argoproj.github.io/argo-helm" }
    - { name: longhorn, url: "https://charts.longhorn.io" }
    - { name: prometheus-community, url: "https://prometheus-community.github.io/helm-charts" }
    - { name: rancher-stable, url: "https://releases.rancher.com/server-charts/stable" }
    - { name: jetstack, url: "https://charts.jetstack.io" }
  tags:
    - apps
    - apps:repos

- import_tasks: rancher.yml
  tags:
    - apps
    - apps:rancher

- import_tasks: traefik.yml
  tags:
    - apps
    - apps:traefik

- import_tasks: authentik.yml
  tags:
    - apps
    - apps:authentik

- import_tasks: argocd.yml
  tags:
    - apps
    - apps:argocd

- import_tasks: longhorn.yml
  tags:
    - apps
    - apps:longhorn

- import_tasks: monitoring.yml
  tags:
    - apps
    - apps:monitoring

