---
- name: Add Rancher Helm repository
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
  register: rancher_repo
  until: rancher_repo is succeeded
  retries: 3
  delay: 10

- name: Check if cert-manager is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
  register: cert_manager_check
  ignore_errors: true

- name: Deploy cert-manager (required for Rancher)
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: v1.8.0
    release_namespace: cert-manager
    create_namespace: yes
    values:
      installCRDs: true
  when: cert_manager_check.resources | length == 0

- name: Wait for cert-manager to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: cert-manager
    label_selectors:
      - app.kubernetes.io/instance=cert-manager
  register: cert_manager_pods
  until: cert_manager_pods.resources | length > 0 and cert_manager_pods.resources | map(attribute='status.phase') | list | unique == ['Running']
  retries: 10
  delay: 30

- name: Check if Rancher is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: rancher
    namespace: cattle-system
  register: rancher_check
  ignore_errors: true

- name: Deploy Rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    chart_version: "{{ rancher_version }}"
    release_namespace: cattle-system
    create_namespace: yes
    values: "{{ lookup('template', 'values-rancher.yaml.j2') | from_yaml }}"
  when: rancher_check.resources | length == 0

- name: Wait for Rancher to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: cattle-system
    label_selectors:
      - app=rancher
  register: rancher_pods
  until: rancher_pods.resources | length > 0 and rancher_pods.resources | map(attribute='status.phase') | list | unique == ['Running']
  retries: 20
  delay: 30