---
- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Restart chrony
  systemd:
    name: chronyd
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart multipathd
  systemd:
    name: multipathd
    state: restarted